# ====================== #
#       ConfigMap        #
# ====================== #

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        sendfile on;
        keepalive_timeout 65;
        include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://blazor-wasm-service/;
      }
      location /api/ {
        proxy_pass http://users-and-auth-service/;
      }
      location /gameplay/ {
        proxy_pass http://gameplay-service/;
      }
    }