# ====================== #
#       ConfigMap        #
# ====================== #

apiVersion: v1
kind: ConfigMap
metadata:
  name: blazor-config
data:
  BLAZOR_SERVER_URL: "http://blazor-server-service"
  GAMEPLAY_URL: "http://gameplay-service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://blazor-client-service/;
        }
        location /api/ {
          proxy_pass http://blazor-server-service/;
        }
        location /gameplay/ {
          proxy_pass http://gameplay-service/;
        }
      }
    }