# ================= #
#     GamePlay      #
# ================= #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameplay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gameplay
  template:
    metadata:
      labels:
        app: gameplay
    spec:
      containers:
        - name: gameplay
          image: chess/gameplay:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: GAMEPLAY_DB_CONNECTION
              value: "Host=gameplay-db;Database=gameplay-db;Username=gameplay;Password=BycRsT3B5PybSd2iaeNV"
            - name: FRONTEND_URL
              value: "http://blazor-client"

---
apiVersion: v1
kind: Service
metadata:
  name: gameplay-service
spec:
  selector:
    app: gameplay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP